# Generated by Django 4.1.5 on 2023-02-07 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'lecteur'), (2, 'annotateur'), (3, 'validateur'), (4, 'admin')], default=1)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(regex='0\\d (\\d{2} ){3}\\d{2}')])),
                ('connecte', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
