# Dockerfile

# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.8

# Mounts the application code to the image
COPY . code
WORKDIR /code


EXPOSE 8000


