# Generated by Django 4.1.5 on 2023-01-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodantInfo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('taille', models.IntegerField()),
                ('phaseLecture', models.IntegerField(blank=True, null=True)),
                ('espece', models.CharField(max_length=200)),
                ('codant_type', models.PositiveSmallIntegerField(choices=[(1, 'CDS'), (2, 'PEP')])),
                ('gene', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('transcript', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_biotype', models.CharField(blank=True, max_length=200, null=True)),
                ('transcript_biotype', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_symbol', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_plasmid', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('taille', models.IntegerField()),
                ('phaseLecture', models.IntegerField(blank=True, null=True)),
                ('espece', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceCodant',
            fields=[
                ('sequence', models.TextField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='genomApp.codantinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceGenome',
            fields=[
                ('sequence', models.TextField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='genomApp.genome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='codantinfo',
            name='chromosome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='genomApp.genome'),
        ),
    ]
