# Generated by Django 4.1.5 on 2023-02-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodantInfo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('taille', models.IntegerField()),
                ('phaseLecture', models.IntegerField(blank=True, null=True)),
                ('espece', models.CharField(max_length=200)),
                ('gc_rate', models.FloatField(blank=True, null=True)),
                ('codant_type', models.PositiveSmallIntegerField(choices=[(1, 'CDS'), (2, 'Peptide')])),
                ('gene', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('transcript', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_biotype', models.CharField(blank=True, max_length=200, null=True)),
                ('transcript_biotype', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_symbol', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_plasmid', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('taille', models.IntegerField()),
                ('phaseLecture', models.IntegerField(blank=True, null=True)),
                ('espece', models.CharField(max_length=200)),
                ('gc_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceCodant',
            fields=[
                ('sequence', models.TextField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='genomApp.codantinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceGenome',
            fields=[
                ('sequence', models.TextField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='genomApp.genome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='codantinfo',
            name='chromosome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='genomApp.genome'),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='genomApp.codantinfo')),
                ('date', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auteur_forum', to='member.member')),
                ('id_chromosome', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='genomApp.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('date_update', models.DateField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auteur_commentaire', to='member.member')),
                ('id_forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='id_forum', to='genomApp.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='genomApp.codantinfo')),
                ('gene', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_symbol', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('already_annotated', models.BooleanField(blank=True, null=True)),
                ('annotateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='annotateur', to='member.member')),
                ('validateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='validateur', to='member.member')),
            ],
        ),
    ]
