# Generated by Django 4.1.5 on 2023-01-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codantinfo',
            name='codant_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CDS'), (2, 'Peptide')]),
        ),
    ]
