name: Genomicus

on:
  push:
    branches:
    - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install sphinx sphinx_rtd_theme Django==4.1.6 fuzzywuzzy==0.18.0 pyfaidx==0.7.1 django-extensions==3.2.1 Bio==1.5.3
      - name: Sphinx Build
        run: |
          sphinx-apidoc --force -o genomicus/docs/source/ genomicus/
          sphinx-build genomicus/docs/source/ _build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          force_orphan: true